// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcvgon9RUSJNMq4N8wHV5TUru8N-Axv3c',
    appId: '1:428716404868:web:8c746af6a299acd9ed92d1',
    messagingSenderId: '428716404868',
    projectId: 'study-buddy-dedde',
    authDomain: 'study-buddy-dedde.firebaseapp.com',
    storageBucket: 'study-buddy-dedde.firebasestorage.app',
    measurementId: 'G-DLMGVSR3D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMW128ZxXUS6jVRriL0yXGVfVn900tvh4',
    appId: '1:428716404868:android:746b021d72f6b711ed92d1',
    messagingSenderId: '428716404868',
    projectId: 'study-buddy-dedde',
    storageBucket: 'study-buddy-dedde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVahCyM_qJVo7u09g8mLy1T-AJ8GGvjuU',
    appId: '1:428716404868:ios:4586cb95e4e9e9aaed92d1',
    messagingSenderId: '428716404868',
    projectId: 'study-buddy-dedde',
    storageBucket: 'study-buddy-dedde.firebasestorage.app',
    iosBundleId: 'com.example.studyBuddyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVahCyM_qJVo7u09g8mLy1T-AJ8GGvjuU',
    appId: '1:428716404868:ios:4586cb95e4e9e9aaed92d1',
    messagingSenderId: '428716404868',
    projectId: 'study-buddy-dedde',
    storageBucket: 'study-buddy-dedde.firebasestorage.app',
    iosBundleId: 'com.example.studyBuddyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcvgon9RUSJNMq4N8wHV5TUru8N-Axv3c',
    appId: '1:428716404868:web:7d12bcfeb1b2cb41ed92d1',
    messagingSenderId: '428716404868',
    projectId: 'study-buddy-dedde',
    authDomain: 'study-buddy-dedde.firebaseapp.com',
    storageBucket: 'study-buddy-dedde.firebasestorage.app',
    measurementId: 'G-0W9S4LYNLP',
  );

}